_target_: src.models.BaseModule
out_channels: 4
net:
  _target_: src.models.UNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 4 # this is the number of classes and should be same as pelvic_frac_yaml file # background, sacrum_fragment, left_hipbone_fragment, right_hipbone_fragment
  channels: [16,32,64]
  strides: [2,2]

# multi_class: true
loss_fn:
  _target_: monai.losses.DiceLoss
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1.0e-3

dice_metric:
  _target_: monai.metrics.DiceMetric
  get_not_nans: true
  ignore_empty: true
iou_metric:
  _target_: monai.metrics.MeanIoU
  get_not_nans: true
  ignore_empty: true
# print(batch_data["image"].shape) # torch.Size([4, 1, 128, 128, 128]) # if batch_size=4
# print(batch_data["label"].shape) # torch.Size([4, 1, 128, 128, 128])
# in_channel is 1 ota since data ma euta batch and euta channel xa
# classes = background lagayera 5 ota xa


# CUDA_VISIBLE_DEVICES=1 python src/train.py experiment=unet.yaml experiment_name=unet_model_training