defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "best"
  monitor: "dice_score_val"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False
  save_top_k: 1 # best model, if topk:2 then top 2 best model is saved

early_stopping:
  monitor: "val/loss"
  patience: 100
  mode: "max"

model_summary:
  max_depth: -1
